import type { Metadata, Viewport } from 'next';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import { Roboto } from 'next/font/google';
import { Box, CssBaseline, ThemeProvider } from '@mui/material';
import { theme } from '@/app/theme';
import { SideMenu } from '@/components/SideMenu';
import { PromptContextProvider } from '@/app/_publicContext/PromptContext';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export const viewport: Viewport = {
    width: 'device-width',
    initialScale: 1,
};

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-roboto',
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    if (!process.env.ANKI_ENDPOINT) {
        return (
            <div>Please configure Anki connect api endpoint in env vars</div>
        );
    }

    return (
        <html lang="en" className={roboto.variable}>
            <body>
                <AppRouterCacheProvider>
                    <ThemeProvider theme={theme}>
                        <PromptContextProvider>
                            <>
                                <CssBaseline />
                                <Box display="flex" flexDirection="row">
                                    <SideMenu />
                                    <Box flexGrow={1} p={3}>
                                        {children}
                                    </Box>
                                </Box>
                            </>
                        </PromptContextProvider>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
